# Use the official Ubuntu image as a base
FROM ubuntu:latest

# Install Python
RUN apt-get update && apt-get install -y python3

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the Python script into the container
COPY main.py .

# Expose port 8000
EXPOSE 8000

# Command to run the HTTP server
CMD ["python3", "main.py"]
